### ISSUE TITLE
Misleading commit ordering

### ISSUE THREAD

**Issue by elliotcm** [alphagov/release#339]
The commits on a given release's page are in commit-date order, but the releases are tagged to merge commits.

This can mean that a commit can appear below a release tag that it wasn't included in, if it was committed earlier than that release but merged later.

For example, in this list, commit `1905d6e0f` appears to be part of `release_4242`, but is actually part of the most recent merge which doesn't yet have a tag.

![image](https://user-images.githubusercontent.com/109225/52779420-fef43180-303f-11e9-9a1c-c71412e47939.png)

Ideally we'd want to be able to properly group commits under their relevant merge commits to give a clearer idea of what changes will go out with a given release tag.

**Comment by sengi** [comment]
Agree this might occasionally cause confusion, but realistically I doubt we'll get around to fixing it as it's low impact and probably high effort to fix. I believe GitHub presents the commit log in essentially the same way, fwiw. And tbf, the page only claims to be a commit log rather than a summary of what was included in which release.

If anyone feels strongly about trying to improve this, perhaps a low-effort partial workaround could be to move the tags into the same column as the commit hash (on the right-hand side of the table) and remove the Tags column. I think that's probably the cue that leads my subconscious to assume that `release_nnnn` is a heading rather than only pertaining to that row's commit.

**Comment by elliotcm** [comment]
If it hasn't been an issue in 5 years I reckon you're all good :)
